---
language: python
os:
  - linux
python:
  - 3.6
  - 3.7
before_install:
  - pip install -r requirements.txt
script:
  - make check
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  on:
    branch: master
