---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Run a one line script
        run: echo "Hello World!"
      - name: Run more lines
        run: |
          echo "more more more"
          echo "more mroe more more"
